services:
  tunnel:
    container_name: tunnel
    image: panubo/sshd:latest
    ports:
      - "127.0.0.1:2222:22"
    volumes:
      - ${WARDEN_HOME_DIR}/tunnel/ssh_key.pub:/etc/authorized_keys/user
      - sshd_keys:/etc/ssh/keys
    environment:
      - |
        MOTD=Welcome to the Warden SSH tunnel container!

        This tunnel container is used only for forwarding TCP
        connections, generally to port 3306 of db containers
        and is not typically used with an interactive shell.

      - SSH_USERS=user:2000:2000
      - TCP_FORWARDING=true
    restart: ${WARDEN_RESTART_POLICY:-always}

volumes:
  sshd_keys:
