services:
  traefik:
    container_name: traefik
    image: traefik:${TRAEFIK_VERSION:-2.2}
    ports:
      - "${TRAEFIK_LISTEN:-127.0.0.1}:80:80"     # The HTTP port
      - "${TRAEFIK_LISTEN:-127.0.0.1}:443:443"   # The HTTPS port
    volumes:
      - ${WARDEN_HOME_DIR}/etc/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ${WARDEN_HOME_DIR}/etc/traefik/dynamic.yml:/etc/traefik/dynamic.yml
      - ${WARDEN_HOME_DIR}/ssl/certs:/etc/ssl/certs
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.rule=Host(`traefik.${WARDEN_SERVICE_DOMAIN:-warden.test}`)
      - traefik.http.routers.traefik.service=api@internal
    restart: ${WARDEN_RESTART_POLICY:-always}
